name: Docker Container
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Target platforms
  PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64

jobs:
  build:
    uses: riesinger/github-workflows/.github/workflows/build-docker.yml@main
    with:
      image-name: plausible-exporter
    secrets: inherit
